version: "3.8"
services:
  db:
    container_name: postgres-db
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - lesson
  testdb:
    container_name: postgres-test-db
    image: postgres:15.1-alpine
    ports:
      - 15434:5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testmydb
    restart: always
  api:
    container_name: app-api
    build: .
    ports:
      - "8080:8080"
      - "2345:2345" #delv（デバッグ）用のポート
    environment:
      GO_ENV: dev
      PORT: 8080
      POSTGRES_USER: user
      POSTGRES_PW: password
      POSTGRES_DB: mydb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db # Dockerでapi起動時
      #POSTGRES_HOST=localhost # ローカル起動時
      SECRET: devsecret
      API_DOMAIN: localhost
    volumes:
      - .:/app
    networks:
      - lesson

volumes:
  db-data:
    driver: local
networks:
  lesson:
    driver: bridge
