name: unit-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres:15.1-alpine
        ports:
          - 15434:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testmydb
        # options: >-
        #   --health-cmd="pg_isready"
        #   --health-interval=10s
        #   --health-timeout=5s
        #   --health-retries=5

    env:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testmydb
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      SECRET: devsecret
      API_DOMAIN: localhost

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        go test -v ./...

